### PR TITLE
email_notifier: Provide text when exception.backtrace is nil

### PR DESCRIPTION
**Pull request by rsuddeth**
Handle empty backtrace the exception from email_notifier.

### CODE REVIEW

**Comment by benlangfeld** [comment]
Excellent, thank you. Could you possibly include a changelog entry for this?

**Comment by rsuddeth** [comment]
@benlangfeld The changeling is updated

**Comment by benlangfeld** [comment]
This needs merge conflicts to be resolved before I can merge it. Perhaps you could do that and squash to a single commit?

**Comment by rsuddeth** [comment]
@benlangfeld, I believe I got the conflict taken care of, but every attempt to squash made it so I was unable to push. I think the only way would be to make a completely new branch and redo the changes. Do you want me to do that?

**Comment by benlangfeld** [comment]
@rsuddeth After squashing you will, of course, have to `git push -f`. That's to be expected. No need for a new branch.

**Comment by rsuddeth** [comment]
@benlangfeld -- it worked!

**Pull request merged**
